language: python
install: "pip install tox coveralls --use-mirrors"

matrix:
  include:
    - python: 2.7
      env: TOXENV=cover
    - python: 2.7
      env: TOXENV=functional
    - python: 2.7
      env: TOXENV=pep8
    - python: 3.4
      env: TOXENV=functional

script: tox
