language: python
install: "pip install tox coveralls --use-mirrors"

matrix:
  include:
    - python: 2.7
      env:
        - TOXENV=cover
        - TOXENV=functional
        - TOXENV=pep8
    - python: 3.4
        - TOXENV=functional

script: tox
